spring.application.name=springdemo

spring.datasource.url=jdbc:postgresql://localhost:5432/fifapp
spring.jpa.properties.hibernate.default_schema=fifapp_credit_new
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

