CREATE TABLE branches (
    id NUMBER(19) NOT NULL,
    branch_code VARCHAR2(20) NOT NULL,
    branch_name VARCHAR2(100) NOT NULL,
    region VARCHAR2(100) NULL,
    city VARCHAR2(100) NULL,
    address VARCHAR2(4000) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT branches_branch_code_key UNIQUE (branch_code),
    CONSTRAINT branches_pkey PRIMARY KEY (id)
);
 
CREATE TABLE customers (
    id NUMBER(19) NOT NULL,
    customer_number VARCHAR2(30) NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    nik VARCHAR2(30) NOT NULL,
    birth_date DATE NULL,
    gender VARCHAR2(20) NULL,
    phone_number VARCHAR2(30) NULL,
    email VARCHAR2(100) NULL,
    address VARCHAR2(4000) NULL,
    city VARCHAR2(100) NULL,
    occupation VARCHAR2(100) NULL,
    monthly_income NUMBER(18, 2) NULL,
    income_range VARCHAR2(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_customers_gender CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE')),
    CONSTRAINT chk_customers_income_range CHECK (income_range IS NULL OR income_range IN ('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH')),
    CONSTRAINT chk_customers_monthly_inc CHECK (monthly_income IS NULL OR monthly_income >= 0),
    CONSTRAINT customers_cust_num_key UNIQUE (customer_number),
    CONSTRAINT customers_nik_key UNIQUE (nik),
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);
 
CREATE TABLE dealers (
    id NUMBER(19) NOT NULL,
    dealer_code VARCHAR2(30) NOT NULL,
    dealer_name VARCHAR2(100) NOT NULL,
    city VARCHAR2(100) NULL,
    region VARCHAR2(100) NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT dealers_dealer_code_key UNIQUE (dealer_code),
    CONSTRAINT dealers_pkey PRIMARY KEY (id),
    CONSTRAINT chk_dealers_is_active CHECK (is_active IN (0, 1))
);
 
CREATE TABLE users (
    id NUMBER(19) NOT NULL,
    branch_id NUMBER(19) NULL,
    employee_number VARCHAR2(30) NOT NULL,
    username VARCHAR2(50) NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    user_role VARCHAR2(50) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_users_role CHECK (user_role IN ('AGENT', 'CREDIT_ANALYST', 'SUPERVISOR', 'ADMIN', 'COLLECTION')),
    CONSTRAINT chk_users_is_active CHECK (is_active IN (0,1)),
    CONSTRAINT users_emp_num_key UNIQUE (employee_number),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_username_key UNIQUE (username),
    CONSTRAINT users_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branches(id)
);
 
CREATE TABLE vehicles (
    id NUMBER(19) NOT NULL,
    dealer_id NUMBER(19) NULL,
    vehicle_code VARCHAR2(30) NOT NULL,
    brand VARCHAR2(100) NOT NULL,
    model VARCHAR2(100) NOT NULL,
    vehicle_type VARCHAR2(50) NULL,
    vehicle_category VARCHAR2(50) NULL,
    production_year NUMBER(4) NULL,
    is_new NUMBER(1) DEFAULT 1 NOT NULL,
    price NUMBER(18, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_vehicles_category CHECK (vehicle_category IS NULL OR vehicle_category IN ('MATIC', 'SPORT', 'SUV', 'MPV', 'COMMERCIAL')),
    CONSTRAINT chk_vehicles_price CHECK (price >= 0),
    CONSTRAINT chk_vehicles_prod_year CHECK (production_year IS NULL OR (production_year >= 1980 AND production_year <= 2100)),
    CONSTRAINT chk_vehicles_type CHECK (vehicle_type IS NULL OR vehicle_type IN ('MOTORCYCLE', 'CAR')),
    CONSTRAINT chk_vehicles_is_new CHECK (is_new IN (0,1)),
    CONSTRAINT vehicles_pkey PRIMARY KEY (id),
    CONSTRAINT vehicles_vehicle_code_key UNIQUE (vehicle_code),
    CONSTRAINT vehicles_dealer_id_fkey FOREIGN KEY (dealer_id) REFERENCES dealers(id)
);
 
CREATE TABLE audit_logs (
    id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NULL,
    entity_name VARCHAR2(100) NOT NULL,
    entity_id NUMBER(19) NOT NULL,
    log_action VARCHAR2(50) NOT NULL,
    old_value VARCHAR2(4000) NULL,
    new_value VARCHAR2(4000) NULL,
    ip_address VARCHAR2(50) NULL,
    user_agent VARCHAR2(4000) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
    CONSTRAINT chk_audit_logs_action CHECK (log_action IN ('CREATE', 'UPDATE', 'DELETE', 'SUBMIT', 'APPROVE', 'REJECT', 'LOGIN', 'PAYMENT')),
    CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);
 
CREATE TABLE credit_applications (
    id NUMBER(19) NOT NULL,
    application_number VARCHAR2(30) NOT NULL,
    customer_id NUMBER(19) NOT NULL,
    vehicle_id NUMBER(19) NOT NULL,
    branch_id NUMBER(19) NOT NULL,
    created_by NUMBER(19) NOT NULL,
    application_date DATE NOT NULL,
    vehicle_price NUMBER(18, 2) NOT NULL,
    dp_amount NUMBER(18, 2) NOT NULL,
    loan_amount NUMBER(18, 2) NOT NULL,
    approved_amount NUMBER(18, 2) NULL,
    tenor_months NUMBER(10) NOT NULL,
    interest_rate NUMBER(5, 2) NULL,
    status VARCHAR2(30) NOT NULL,
    submitted_at TIMESTAMP NULL,
    approved_at TIMESTAMP NULL,
    rejected_at TIMESTAMP NULL,
    manual_review_at TIMESTAMP NULL,
    cancelled_at TIMESTAMP NULL,
    decision_reason VARCHAR2(4000) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_cred_app_amounts CHECK (vehicle_price >= 0 AND dp_amount >= 0 AND loan_amount >= 0 AND (approved_amount IS NULL OR approved_amount >= 0)),
    CONSTRAINT chk_cred_app_interest CHECK (interest_rate IS NULL OR interest_rate >= 0),
    CONSTRAINT chk_cred_app_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'MANUAL_REVIEW', 'CANCELLED')),
    CONSTRAINT chk_cred_app_tenor CHECK (tenor_months > 0),
    CONSTRAINT cred_app_app_num_key UNIQUE (application_number),
    CONSTRAINT credit_applications_pkey PRIMARY KEY (id),
    CONSTRAINT cred_app_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT cred_app_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT cred_app_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT cred_app_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);
 
CREATE TABLE installments (
    id NUMBER(19) NOT NULL,
    credit_application_id NUMBER(19) NOT NULL,
    installment_number NUMBER(10) NOT NULL,
    due_date DATE NOT NULL,
    amount NUMBER(18, 2) NOT NULL,
    paid_amount NUMBER(18, 2) DEFAULT 0 NOT NULL,
    outstanding_amount NUMBER(18, 2) NULL,
    payment_date DATE NULL,
    days_overdue NUMBER(10) DEFAULT 0 NOT NULL,
    status VARCHAR2(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_inst_amount CHECK (amount >= 0 AND paid_amount >= 0 AND (outstanding_amount IS NULL OR outstanding_amount >= 0)),
    CONSTRAINT chk_inst_days_overdue CHECK (days_overdue >= 0),
    CONSTRAINT chk_inst_number CHECK (installment_number > 0),
    CONSTRAINT chk_inst_status CHECK (status IN ('UNPAID', 'PARTIAL_PAID', 'PAID', 'LATE', 'DEFAULTED')),
    CONSTRAINT installments_pkey PRIMARY KEY (id),
    CONSTRAINT uq_inst_app_num UNIQUE (credit_application_id, installment_number),
    CONSTRAINT inst_cred_app_id_fkey FOREIGN KEY (credit_application_id) REFERENCES credit_applications(id)
);
 
CREATE TABLE payments (
    id NUMBER(19) NOT NULL,
    installment_id NUMBER(19) NOT NULL,
    paid_by NUMBER(19) NULL,
    payment_number VARCHAR2(30) NOT NULL,
    payment_date DATE NOT NULL,
    payment_amount NUMBER(18, 2) NOT NULL,
    payment_method VARCHAR2(50) NULL,
    payment_channel VARCHAR2(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_payments_amount CHECK (payment_amount > 0),
    CONSTRAINT chk_payments_channel CHECK (payment_channel IS NULL OR payment_channel IN ('BRANCH', 'MOBILE_APP', 'BANK', 'PARTNER')),
    CONSTRAINT chk_payments_method CHECK (payment_method IS NULL OR payment_method IN ('CASH', 'TRANSFER', 'VIRTUAL_ACCOUNT', 'AUTODEBIT')),
    CONSTRAINT payments_payment_number_key UNIQUE (payment_number),
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT payments_installment_id_fkey FOREIGN KEY (installment_id) REFERENCES installments(id),
    CONSTRAINT payments_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES users(id)
);
 
CREATE TABLE risk_assessments (
    id NUMBER(19) NOT NULL,
    credit_application_id NUMBER(19) NOT NULL,
    assessed_by NUMBER(19) NULL,
    risk_score NUMBER(10) NULL,
    risk_level VARCHAR2(30) NULL,
    decision VARCHAR2(30) NOT NULL,
    income_score NUMBER(10) NULL,
    age_score NUMBER(10) NULL,
    loan_amount_score NUMBER(10) NULL,
    dbr_score NUMBER(10) NULL,
    previous_payment_score NUMBER(10) NULL,
    dbr_percentage NUMBER(5, 2) NULL,
    notes VARCHAR2(4000) NULL,
    assessed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_risk_ass_dbr CHECK (dbr_percentage IS NULL OR dbr_percentage >= 0),
    CONSTRAINT chk_risk_ass_decision CHECK (decision IN ('APPROVED', 'REJECTED', 'MANUAL_REVIEW')),
    CONSTRAINT chk_risk_ass_risk_level CHECK (risk_level IS NULL OR risk_level IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_risk_ass_score CHECK (risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)),
    CONSTRAINT risk_ass_cred_app_id_key UNIQUE (credit_application_id),
    CONSTRAINT risk_assessments_pkey PRIMARY KEY (id),
    CONSTRAINT risk_ass_assessed_by_fkey FOREIGN KEY (assessed_by) REFERENCES users(id),
    CONSTRAINT risk_ass_cred_app_id_fkey FOREIGN KEY (credit_application_id) REFERENCES credit_applications(id)
);