CREATE INDEX idx_customer_full_name ON customers (full_name);
CREATE INDEX idx_customers_city ON customers (city);
CREATE INDEX idx_customers_income_range ON customers (income_range);
CREATE INDEX idx_dealers_city ON dealers (city);
CREATE INDEX idx_dealers_region ON dealers (region);
CREATE INDEX idx_vehicles_brand ON vehicles (brand);
CREATE INDEX idx_vehicles_brand_model ON vehicles (brand, model);
CREATE INDEX idx_vehicles_dealer_id ON vehicles (dealer_id);
CREATE INDEX idx_vehicles_model ON vehicles (model);
CREATE INDEX idx_vehicles_veh_cat ON vehicles (vehicle_category);
CREATE INDEX idx_vehicles_veh_type ON vehicles (vehicle_type);
CREATE INDEX idx_audit_logs_action ON audit_logs (log_action);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);
CREATE INDEX idx_audit_logs_ent_name_id ON audit_logs (entity_name, entity_id);
CREATE INDEX idx_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX idx_cr_app_date ON credit_applications (application_date);
CREATE INDEX idx_cr_app_branch_id ON credit_applications (branch_id);
CREATE INDEX idx_cr_app_created_by ON credit_applications (created_by);
CREATE INDEX idx_cr_app_customer_id ON credit_applications (customer_id);
CREATE INDEX idx_cr_app_status ON credit_applications (status);
CREATE INDEX idx_cr_app_vehicle_id ON credit_applications (vehicle_id);
CREATE INDEX idx_inst_cred_app_id ON installments (credit_application_id);
CREATE INDEX idx_inst_due_date ON installments (due_date);
CREATE INDEX idx_inst_status ON installments (status);
CREATE INDEX idx_inst_stat_due ON installments (status, due_date);
CREATE INDEX idx_payments_installment_id ON payments (installment_id);
CREATE INDEX idx_payments_meth_chan ON payments (payment_method, payment_channel);
CREATE INDEX idx_payments_paid_by ON payments (paid_by);
CREATE INDEX idx_payments_payment_date ON payments (payment_date);
CREATE INDEX idx_risk_ass_at ON risk_assessments (assessed_at);
CREATE INDEX idx_risk_ass_by ON risk_assessments (assessed_by);
CREATE INDEX idx_risk_ass_decision ON risk_assessments (decision);
CREATE INDEX idx_risk_ass_level ON risk_assessments (risk_level);